#!/bin/sh

set -e

export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
  nvm use --silent >/dev/null 2>&1 || true
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

pnpm lint-staged
git update-index --again
echo "✨ ${GREEN}Done - HUSKY_PRE_COMMIT${NC}"
